import '@radix-ui/themes/styles.css';
import './theme-config.css'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'
import { SpeedInsights } from "@vercel/speed-insights/next"
const inter = Inter({ subsets: ['latin'],
variable: '--font-inter' 
})

import { Theme, ThemePanel } from '@radix-ui/themes';


export const metadata: Metadata = {
  title: "Kyle's Data Submission Site",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
      <Theme appearance="light" accentColor="teal" scaling="110%">
          <NavBar/>
          <main className="p-5">
            {children}
          </main>
        </Theme>
        </body>
    </html>
  )
}
